#!/bin/bash
greentext="\033[32m"
normal="\033[0m"
logdate=$(date +"%Y%m%d%H:%M:%S")
logfile="$logdate"_report.log

cat <<- EOF > $logfile
	This report was automatically generated by my Bash script.
	It contains a brief summary of some system information.
EOF

mv  $logfile moved_to
echo -e $greentext"A summary of this info has been saved to $logfile"$normal